###

GET https://api.github.com/repos/microsoft/vscode/issues?state=closed&labels=insiders-released&pulls=true&page=1
Accept: application/vnd.github+json
Authorization: Bearer {{gh-api-token}}
X-GitHub-Api-Version: 2022-11-28

###

GET https://api.github.com/repos/microsoft/vscode/pulls?state=closed&page=1
Accept: application/vnd.github+json
Authorization: Bearer {{gh-api-token}}


#&page=236
# https://github.com/microsoft/vscode/issues?q=is:issue+is:closed+reason:completed+label:insiders-released
# https://github.com/microsoft/vscode/pulls?q=is:pr+is:merged&page=1

# is:pr is:merged

###

curl --request GET \
--url 'https://api.github.com/repos/microsoft/vscode/issues?state=closed&labels=insiders-released&pulls=true&page=1' \
--header 'accept: application/vnd.github+json' \
--header 'authorization: Bearer '${{gh-api-token}} \
--header 'user-agent: vscode-restclient'
